- name: taskrepo
  type: git
  source:
    uri: https://github.com/amoolramesh/concourse.git
    branch: main
    username: amoolramesh11@gmail.com
    password: Git@2023

- name: gdt
  type: docker-image
  source:
    repository: 23380/test-image-6

jobs:

jobs:
# update this pipeline before updating child pipelines
- name: set-self
  public: true
  plan:
  - get: taskrepo
    trigger: true
  - set_pipeline: self
    file: concourse/pipelines.yml

- name: deploy
  public: true
  plan:
  - get: taskrepo
  - get: gdt
    trigger: true
    passed: [set-self]
  - set_pipeline: job
    file: concourse/ci/tasks/run-docker.yml
